{% set name = "freepascal" %}
{% set version = "3.0.4" %}
{% set checksum = "69b3b7667b72b6759cf27226df5eb54112ce3515ff5efb79d95ac14bac742845" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/freepascal/files/Source/3.0.4/fpc-3.0.4.source.tar.gz/download
  sha256: {{ checksum }}

build:
  number: 0
  script_env:
      - CONDA_BLD_PATH

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.0
    - swig
    - ninja
    - boost-cpp
    - zeromq
    - python
  host:
    - python
    - boost-cpp
    - zeromq
  run:
    - python
    - boost-cpp
    - zeromq

about:
  home: https://www.freepascal.org/
  license: GNU General Public License
  license_file: LICENSE
  license_family: GNU General Public License
  summary: 'FreePascal'
  description: 'FreePascal'

extra:
  recipe-maintainers:
    - kdheepak
