{% set name = "freepascal" %}
{% set version = "3.0.4" %}
{% set checksum = "69b3b7667b72b6759cf27226df5eb54112ce3515ff5efb79d95ac14bac742845" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/freepascal/Source/3.0.4/fpc-3.0.4.source.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script_env:
      - CONDA_BLD_PATH

requirements:
  build:
    - make  # [windows]
  host:
    - make  # [windows]

test:
  commands:
    - fpc -h

about:
  home: https://www.freepascal.org/
  license: GPL
  license_file: compiler/COPYING.txt
  license_family: GPL
  summary: 'FreePascal'
  description: 'FreePascal'

extra:
  recipe-maintainers:
    - kdheepak
